version: "3.8"
services:

  haproxy:
    image: haproxy:2.8-alpine

    container_name: dwcHaproxy

    restart: always

    ports:
      - 80:80

    volumes:
     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  dns:
    build:
      context: dnsmasq

    container_name: dwcDns

    ports:
      - 53:53/udp
      - 53:53

    environment:
      HOST_IP: ${HOST_IP?Missing environment variable see readme}
      PRIMARY_FORWARD_DNS: ${PRIMARY_FORWARD_DNS-8.8.8.8}
      SECONDARY_FORWARD_DNS: ${SECONDARY_FORWARD_DNS-8.8.4.4}

    restart: always

  dwc:
    build:
      context: dwc

    container_name: dwcServer

    restart: always

    environment:
      DWC_ADMIN_USERNAME: ${DWC_ADMIN_USERNAME?Missing environment variable see readme}
      DWC_ADMIN_PASSWORD: ${DWC_ADMIN_PASSWORD?Missing environment variable see readme}

    ports:
      - 8000:8000       # StorageServer
      - 9000:9000       # NasServer
      - 9001:9001       # InternalStatsServer
      - 27500:27500     # GameSpyManager
      - 28910:28910     # GameSpyServerBrowserServer
      - 29900:29900     # GameSpyProfileServer
      - 29901:29901     # GameSpyPlayerSearchServer
      - 29920:29920     # GameSpyGamestatsServer
      - 27900:27900/udp # GameSpyQRServer
      - 27901:27901/udp # GameSpyNatNegServer
      - 9003:9003       # Dls1Server
      - 9009:9009       # AdminPage
      - 9998:9998       # RegisterPage

    volumes:
      - dwcData:/dwc/data

volumes:
  dwcData:
    driver: local
